# Examples

In [2]:
import numpy as np

In [5]:
# throwing a coin 1 time (0 is tail 1 is heads)
np.random.randint(low=0,high=2,size=1)     # her calistirmada farkli deger uretir

array([1])

In [11]:
# throwing a coin 10 times ( 0 is tail 1 is heads)
coin = np.random.randint(0,2,size=10)
print(coin)
print(coin.sum())

[1 1 0 1 0 0 0 1 1 1]
6


In [8]:
# Her satir 10 atis 
coin_matrix=np.random.randint(0,2,size=(10000,10))   # 10000 satir olacak 10 sutun olacak
coin_matrix[:5,:]         # ilk 5 satiri getirecek ve tum sutunlar

array([[0, 0, 0, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 0, 1, 1, 0],
       [1, 0, 1, 1, 1, 1, 0, 1, 0, 0]])

In [9]:
counts = coin_matrix.sum(axis=1)   # axis=1 satirlari toplamak icin axis=0 olsaydi sutunun tamamini toplardi 
print(counts[:25])    # 25 satirin tek tek toplami
print(counts.mean())     # ortalamasi
print(np.median(counts))  # tam ortadaki deger
print(counts.min(),counts.max())
print(counts.std())  # standart sapma 

[4 4 3 7 6 5 5 4 3 5 2 6 7 7 7 5 5 5 5 3 4 7 8 5 4]
5.019
5.0
0 10
1.5652600422932927


In [12]:
np.bincount(counts)  # tek satirda kac kere 0 gorulmus 

array([  12,   87,  422, 1132, 2086, 2404, 2139, 1171,  460,   82,    5],
      dtype=int64)

In [13]:
unique_numbers = np.arange(0,11) # ust satirdaki 11 tane rakamdan dolayi yapilmis
observed_times = np.bincount(counts)
print('============\n')
for n,count in zip(unique_numbers,observed_times):
    print('{} heads observed {} times ({:0.1f}%)'.format(n,count,100*count/2000))


0 heads observed 12 times (0.6%)
1 heads observed 87 times (4.3%)
2 heads observed 422 times (21.1%)
3 heads observed 1132 times (56.6%)
4 heads observed 2086 times (104.3%)
5 heads observed 2404 times (120.2%)
6 heads observed 2139 times (107.0%)
7 heads observed 1171 times (58.5%)
8 heads observed 460 times (23.0%)
9 heads observed 82 times (4.1%)
10 heads observed 5 times (0.2%)
