# NumPy 

In [6]:
import numpy as np

## Creating arrays : from lists and using built-in functions

In [7]:
# arrays from list
distances = [10,15,17,26,20]
times = [0.3,0.47,0.55,1.20,1.0]
distances = np.array(distances)
times = np.array(times)

In [8]:
product_quantities = [13,5,6,10,11]
prices = [1.2,6.5,1.0,4.8,5.0]
product_quantities = np.array(product_quantities)
prices = np.array(prices)

In [9]:
distances

array([10, 15, 17, 26, 20])

In [10]:
type(distances)

numpy.ndarray

In [12]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [13]:
# create a lenght-10 integer array filled with zeros
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
#create a 4x5 floating-point array filled with ones
np.ones(shape=(4,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
#create an array filled with a linear squence
#Starting at 0 ending at 30 stepping by 2
np.arange(start=0,stop=30,step=2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [16]:
#create an array of 20 values evenly spaced between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Some attributes of array

In [18]:
a = np.ones(shape=(3,4),dtype=float)
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
a.ndim #number of dimensions

2

In [20]:
a.shape

(3, 4)

In [21]:
a.size

12

## Basic math with arrays

#### distances = [10,15,17,26,20] 
#### times = [0.3,0.47,0.55,1.20,1.0]

In [23]:
speeds = distances/times
speeds

array([33.33333333, 31.91489362, 30.90909091, 21.66666667, 20.        ])

#### product_quantities = [13,5,6,10,11]
#### prices = [1.2,6.5,1.0,4.8,5.0]

In [24]:
values = product_quantities * prices
total = values.sum()
print(values)
total

[15.6 32.5  6.  48.  55. ]


157.1

In [25]:
x = np.arange(0,20,2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
x + 1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [27]:
x * 2 

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [28]:
x / 2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [29]:
np.sin(x)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725])

In [30]:
np.exp(x)

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
       8.88611052e+06, 6.56599691e+07])

In [31]:
np.log(x+1)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])

In [32]:
np.sqrt(x)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069])

## indexing

In [34]:
one_dim = np.linspace(-0.5,0.6,12)
one_dim

array([-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6])

In [35]:
one_dim[0]

-0.5

In [36]:
one_dim[0] = 1 
one_dim

array([ 1. , -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6])

In [38]:
two_dim = np.array([[2,3,4,5],[6,7,4,5],[-1,1,9,-1]])
two_dim

array([[ 2,  3,  4,  5],
       [ 6,  7,  4,  5],
       [-1,  1,  9, -1]])

In [39]:
two_dim[0,3]

5

In [40]:
two_dim[0,0]= -1
two_dim

array([[-1,  3,  4,  5],
       [ 6,  7,  4,  5],
       [-1,  1,  9, -1]])

## Slicing

In [41]:
one_dim

array([ 1. , -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6])

In [42]:
print(one_dim[2:5])
print(one_dim[:5])
print(one_dim[-5:])

[-0.3 -0.2 -0.1]
[ 1.  -0.4 -0.3 -0.2 -0.1]
[0.2 0.3 0.4 0.5 0.6]


In [43]:
two_dim

array([[-1,  3,  4,  5],
       [ 6,  7,  4,  5],
       [-1,  1,  9, -1]])

In [46]:
two_dim[:2,:2]

array([[-1,  3],
       [ 6,  7]])

In [47]:
two_dim[:,1:3]

array([[3, 4],
       [7, 4],
       [1, 9]])

# Reshaping

In [48]:
one_dim

array([ 1. , -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6])

In [49]:
one_dim.reshape(3,4)

array([[ 1. , -0.4, -0.3, -0.2],
       [-0.1,  0. ,  0.1,  0.2],
       [ 0.3,  0.4,  0.5,  0.6]])

In [50]:
two_dim

array([[-1,  3,  4,  5],
       [ 6,  7,  4,  5],
       [-1,  1,  9, -1]])

In [51]:
two_dim.flatten()

array([-1,  3,  4,  5,  6,  7,  4,  5, -1,  1,  9, -1])