# Numpy Giris

In [216]:
import numpy as np

In [217]:
a = np.array ([1,2,3,4])
b = np.array ([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

In [218]:
x = 9

In [219]:
who

L	 M	 a	 al_getir	 alt	 alt_a	 alt_b	 b	 c	 
i	 index	 m	 np	 sag	 satir	 sol	 sutun	 ust	 
v	 x	 y	 z	 


In [220]:
x

9

In [221]:
L = [1,2,'a',1.2]
L

[1, 2, 'a', 1.2]

In [222]:
[type(i) for i in L]

[int, int, str, float]

# Numpy Array Olusturma

## Listelerden Array olusturma

In [223]:
import numpy as np
np.array ([12,33,4,5])

a = np.array ([12,33,4,5])
a

array([12, 33,  4,  5])

In [224]:
type(a)

numpy.ndarray

In [225]:
np.array([3.14,4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])

In [226]:
np.array([3.14,4,6,1.2], dtype = 'float')

array([3.14, 4.  , 6.  , 1.2 ])

In [227]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [228]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [229]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [230]:
np.full((2,3),9)

array([[9, 9, 9],
       [9, 9, 9]])

In [231]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [232]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [233]:
np.random.normal(0,1,(3,4)) # normal dagilimli ortalama = 0 standart sapma = 1

array([[ 1.35522714,  0.958543  ,  0.62909114, -1.17579306],
       [-1.71416389, -0.53447788,  0.20415538, -1.4577192 ],
       [ 0.40701458, -2.18618514, -2.56544572, -1.16402302]])

In [234]:
np.random.randint(0,10,(2,2))

array([[4, 0],
       [6, 0]])

In [235]:
np.eye(3) # identity matrisi

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Numpy Bicimlendirme

* **ndim** : boyut sayisi
* **shape** : boyut bilgisi
* **size** : toplam eleman sayisi
* **dtype** : array veri tipi

In [236]:
import numpy as np
a = np.random.randint(10,size = 10)
a.ndim
a.shape
a.size
a.dtype

dtype('int32')

In [237]:
a = np.random.randint(10,size = (10,5))
a

array([[1, 4, 6, 4, 2],
       [5, 4, 3, 3, 2],
       [3, 2, 5, 5, 9],
       [4, 8, 2, 8, 7],
       [0, 5, 4, 0, 7],
       [6, 0, 7, 0, 5],
       [9, 4, 4, 0, 2],
       [0, 3, 3, 4, 3],
       [3, 7, 1, 7, 3],
       [4, 1, 0, 3, 7]])

In [238]:
a.ndim
a.size
a.shape
a.dtype

dtype('int32')

In [239]:
a = np.random.randint(10,size = (3,5,2))
a

array([[[5, 3],
        [8, 5],
        [4, 8],
        [0, 9],
        [6, 8]],

       [[4, 0],
        [3, 1],
        [9, 7],
        [1, 3],
        [6, 2]],

       [[6, 5],
        [9, 6],
        [9, 1],
        [9, 2],
        [4, 9]]])

In [240]:
a.ndim

3

In [241]:
a.size

30

In [242]:
a.shape

(3, 5, 2)

In [243]:
a.dtype

dtype('int32')

In [244]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [245]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [246]:
a = np.array([1,2,3])

In [247]:
a

array([1, 2, 3])

In [248]:
b = a.reshape((1,3)) # vektirden matrise cevirdik onemli !!
b

array([[1, 2, 3]])

In [249]:
b.ndim

2

In [250]:
a

array([1, 2, 3])

In [251]:
a[np.newaxis,:] #3 ust satirla ayni islem

array([[1, 2, 3]])

In [252]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

### Array birlestirme

In [253]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [254]:
x

array([1, 2, 3])

In [255]:
y

array([4, 5, 6])

In [256]:
#Tek boyutlu

In [257]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [258]:
z = [1,2,3]

In [259]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [260]:
a = np.array([[1,2,3],
             [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [261]:
# iki boyutlu

In [262]:
np.concatenate([a,a]) # satir bazinda birlestirdi

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [263]:
np.concatenate([a,a],axis=1) # sutun bazinda

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [264]:
# Farkli boyutlu

In [265]:
a = np.array([1,2,3])
b = np.array([[9,8,7],
             [6,5,4]])

In [266]:
a

array([1, 2, 3])

In [267]:
b

array([[9, 8, 7],
       [6, 5, 4]])

In [268]:
np.vstack([a,b]) #satir bazinda

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [269]:
a = np.array([[99],
              [99]])

In [270]:
a

array([[99],
       [99]])

In [271]:
np.hstack([a,b]) #sutun bazinda

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

### Array Ayirma

In [272]:
x = [1,2,3,99,99,3,2,1]
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [273]:
np.split(x,[3,5])  # 3. v 5. indexlerden bolduk

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [274]:
a,b,c = np.split(x,[3,5])

In [275]:
a

array([1, 2, 3])

In [276]:
b

array([99, 99])

In [277]:
c

array([3, 2, 1])

In [278]:
m = np.arange(16).reshape((4,4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [279]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [280]:
ust,alt =np.vsplit(m,[2])

In [281]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [282]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [283]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [284]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [285]:
sol,sag = np.hsplit(m,[2])

In [286]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [287]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### Array siralama

In [288]:
v = np.array ([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [289]:
np.sort(v) # gecici siraladik

array([1, 2, 3, 4, 5])

In [290]:
v

array([2, 1, 4, 3, 5])

In [291]:
v.sort() # kalici olarak siraladik

In [292]:
v

array([1, 2, 3, 4, 5])

In [293]:
v = np.array ([2,1,4,3,5])

In [294]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [295]:
i = np.argsort(v) # siralama sonrasinda index durumlari ne olur. OLUMCUL ONEMLI !!!

In [296]:
i

array([1, 0, 3, 2, 4], dtype=int64)

In [297]:
v

array([2, 1, 4, 3, 5])

In [298]:
v[i]

array([1, 2, 3, 4, 5])

# Numpy Eleman Islemleri

In [299]:
a = np.random.randint(10,size=10)
a

array([0, 7, 6, 6, 6, 1, 3, 7, 8, 1])

In [300]:
a[0]

0

In [301]:
a[-1]

1

In [302]:
a[0] = 1

In [303]:
a

array([1, 7, 6, 6, 6, 1, 3, 7, 8, 1])

In [304]:
a = np.random.randint(10,size=(3,5))
a

array([[6, 0, 0, 4, 8],
       [2, 5, 6, 9, 1],
       [7, 9, 6, 8, 4]])

In [305]:
a[0,0]

6

In [306]:
a[1,1]

5

In [307]:
a[0,0] = 1

In [308]:
a[0,0]

1

In [309]:
a[0,0] = 2.2 # float ekledik ama tek tip olmak zorunda oldugundan int e cevirdi

In [310]:
a[0,0]

2

## Slicing ile alt kumeye erisme

In [311]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [312]:
a[0:3]

array([20, 21, 22])

In [313]:
a[:3]

array([20, 21, 22])

In [314]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [315]:
a[::2]

array([20, 22, 24, 26, 28])

In [316]:
a[1::2]

array([21, 23, 25, 27, 29])

In [317]:
a[2::2]

array([22, 24, 26, 28])

In [318]:
a = np.random.randint(10, size = (5,5))
a

array([[1, 8, 0, 8, 6],
       [0, 7, 8, 9, 6],
       [4, 3, 0, 7, 1],
       [1, 2, 1, 9, 5],
       [7, 9, 7, 1, 8]])

In [319]:
a[:,0]

array([1, 0, 4, 1, 7])

In [320]:
a[:,1]

array([8, 7, 3, 2, 9])

In [321]:
a[0,:]

array([1, 8, 0, 8, 6])

In [322]:
a[0]

array([1, 8, 0, 8, 6])

In [323]:
a[:2,:3]

array([[1, 8, 0],
       [0, 7, 8]])

In [324]:
a[0:2,0:3]

array([[1, 8, 0],
       [0, 7, 8]])

In [325]:
a[:,:2]

array([[1, 8],
       [0, 7],
       [4, 3],
       [1, 2],
       [7, 9]])

In [326]:
a[1:3,0:2]

array([[0, 7],
       [4, 3]])

In [327]:
a = np.random.randint(10, size= (5,5))
a

array([[1, 5, 3, 2, 8],
       [6, 5, 5, 3, 8],
       [2, 6, 8, 8, 5],
       [1, 8, 9, 7, 5],
       [7, 4, 6, 4, 4]])

In [328]:
alt_a = a[0:3,0:2]

In [329]:
alt_a

array([[1, 5],
       [6, 5],
       [2, 6]])

In [330]:
alt_a [0,0] = 9999  # alt kumede degisiklik yapinca ana kumenin ilk hali de degisir
alt_a [1,1] = 9999

In [331]:
alt_a

array([[9999,    5],
       [   6, 9999],
       [   2,    6]])

In [332]:
a

array([[9999,    5,    3,    2,    8],
       [   6, 9999,    5,    3,    8],
       [   2,    6,    8,    8,    5],
       [   1,    8,    9,    7,    5],
       [   7,    4,    6,    4,    4]])

In [333]:
a = np.random.randint(10, size= (5,5))
a

array([[9, 8, 0, 9, 0],
       [3, 7, 4, 6, 0],
       [9, 0, 9, 4, 6],
       [8, 8, 6, 2, 4],
       [6, 5, 4, 9, 8]])

In [334]:
alt_b = a[0:3,0:2].copy()
alt_b

array([[9, 8],
       [3, 7],
       [9, 0]])

In [335]:
alt_b[0,0] = 9999
alt_b[1,1] = 9999

In [336]:
a

array([[9, 8, 0, 9, 0],
       [3, 7, 4, 6, 0],
       [9, 0, 9, 4, 6],
       [8, 8, 6, 2, 4],
       [6, 5, 4, 9, 8]])

## Fancy index ile Eleman islemleri

In [337]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [338]:
v[1]
v[3]

9

In [339]:
[v[1],v[3]]

[3, 9]

In [340]:
al_getir = [1,3,5]

In [341]:
v[al_getir]

array([ 3,  9, 15])

In [342]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [343]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [344]:
m[satir,sutun]

array([1, 5])

In [345]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [346]:
m[0,[1,2]]

array([1, 2])

In [347]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [348]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [349]:
index = np.array([0,1,2])
index

array([0, 1, 2])

In [350]:
v[index]

array([0, 1, 2])

In [351]:
v[index] = 99

In [352]:
v

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [353]:
v[[0,1]] = [4,6]

In [354]:
v

array([ 4,  6, 99,  3,  4,  5,  6,  7,  8,  9])

## Kosullu eleman Islemleri

In [355]:
v = np.array([1,2,3,4,5])

In [356]:
v > 3

array([False, False, False,  True,  True])

In [357]:
v < 3

array([ True,  True, False, False, False])

In [358]:
v == 3

array([False, False,  True, False, False])

In [359]:
2 * v

array([ 2,  4,  6,  8, 10])

In [360]:
(v **2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [361]:
(2 * v) == (v**2)

array([False,  True, False, False, False])

In [362]:
#ufunc

* np.equal
* np.not_equal
* np.less
* np.less_equal
* np.greater
* np.greater_equal

In [363]:
v = np.array([1,2,3,4,5])

In [364]:
np.equal(3,v)

array([False, False,  True, False, False])

In [365]:
np.equal([0,1,3],np.arange(3))

array([ True,  True, False])

In [366]:
v = np.random.randint(0,10,(3,3))
v

array([[2, 3, 0],
       [9, 5, 8],
       [3, 8, 2]])

In [367]:
v > 5

array([[False, False, False],
       [ True, False,  True],
       [False,  True, False]])

In [368]:
np.sum(v > 5)

3

In [369]:
np.sum((v > 3) & (v <7))

1

In [370]:
(v > 3) & (v <7)

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [371]:
np.sum((v > 3) | (v <7))

9

In [372]:
np.sum(v>4, axis = 1) #satirda saglayanlar

array([0, 3, 1])

In [373]:
np.sum(v>4, axis = 0)

array([1, 2, 1])

In [374]:

np.all( v> 4) # Tum elemanlar icin

False

In [375]:
np.any(v>4) # herhangi bir elemanin sarti saglayip saglamadigi

True

In [376]:
v

array([[2, 3, 0],
       [9, 5, 8],
       [3, 8, 2]])

In [377]:
np.any(v>4, axis= 1) # satir

array([False,  True,  True])

In [378]:
np.any(v>4, axis= 0) # sutun

array([ True,  True,  True])

In [379]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [380]:
v[0]

1

In [381]:
v>3

array([False, False, False,  True,  True])

In [382]:
v[v >3]

array([4, 5])

In [383]:
v [ (v > 1 ) & (v <5)]

array([2, 3, 4])

# Numpy Hesaplamali islemler

In [384]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [385]:
a -1

array([-1,  0,  1,  2,  3])

In [386]:
a /2

array([0. , 0.5, 1. , 1.5, 2. ])

In [387]:
a * 5

array([ 0,  5, 10, 15, 20])

In [388]:
a ** 5

array([   0,    1,   32,  243, 1024], dtype=int32)

In [389]:
a % 2 

array([0, 1, 0, 1, 0], dtype=int32)

In [390]:
5 * (a/2 * 9)

array([ 0. , 22.5, 45. , 67.5, 90. ])

In [391]:
a

array([0, 1, 2, 3, 4])

In [392]:
np.add(a,2)

array([2, 3, 4, 5, 6])

In [393]:
np.subtract(a,1)

array([-1,  0,  1,  2,  3])

In [394]:
np.multiply(a,3)

array([ 0,  3,  6,  9, 12])

In [395]:
np.divide(a,3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [396]:
np.power(a,3)

array([ 0,  1,  8, 27, 64], dtype=int32)

In [397]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [398]:
np.add.reduce(a)

15

In [399]:
np.add.accumulate(a)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [400]:
a = np.random.normal(0,1,30)
a

array([ 0.62120783, -0.90686725, -0.11400383, -0.01200423, -0.38696522,
       -1.77491943,  0.63357092, -0.18186627, -0.08104398,  1.59923619,
       -0.47388728,  1.42365015, -0.48353204,  0.18636958, -0.92939843,
        1.16442041, -0.73444691, -0.57612781,  1.04046457,  1.48597544,
        0.28280383, -0.64523268, -1.20574642,  0.4935343 ,  1.04713858,
        1.5850683 , -0.20142036, -1.67455253,  0.55800085,  0.41250972])

In [401]:
np.mean(a)

0.07173120047510087

In [402]:
np.std(a)

0.9200764015057976

In [403]:
np.var(a)

0.8465405846078576

In [404]:
np.median(a)

-0.04652410281541505

In [405]:
sum(a)

2.151936014253026

* np.nanmean(a)
* np.nanstd(a)
* np.nanvar(a)
* np.nanargmin(a)
* np.nanargmac(a)
* np.nanmedian(a) # Eksik degerlere duyarli versiyonlar... 

In [406]:
np.min(a)

-1.7749194339074468

In [407]:
np.max(a)

1.5992361928405299

In [408]:
a = np.random.normal(0,1,(3,3))
a

array([[-0.33834318, -1.73312096, -1.00747428],
       [-0.72021767, -0.88744203,  0.13542046],
       [-0.74879397,  0.65783055,  0.18757146]])

In [409]:
a.sum()

-4.45456963774357

In [410]:
a.sum(axis = 1)

array([-3.07893842, -1.47223925,  0.09660803])

# Farkli Boyutlu Arraylar ile Birlikte Calismak (Broadcasting)

In [411]:
a = np.array([1,2,3])
b = np.array([1,2,3])

a + b

array([2, 4, 6])

In [412]:
m = np.ones((3,3))
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [413]:
a

array([1, 2, 3])

In [414]:
a + m

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [415]:
a = np.arange(3)
a

array([0, 1, 2])

In [416]:
b = np.arange(3)[:,np.newaxis]
b

array([[0],
       [1],
       [2]])

In [417]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [418]:
M = np.ones((2,3))
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [419]:
a = np.arange(3)
a

array([0, 1, 2])

In [420]:
a + M

array([[1., 2., 3.],
       [1., 2., 3.]])

In [421]:
a = np.arange(3).reshape((3,1))
a

array([[0],
       [1],
       [2]])

In [422]:
b = np.arange(3)
b

array([0, 1, 2])

In [423]:
a.shape

(3, 1)

In [424]:
b.shape

(3,)

In [425]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [426]:
m = np.ones((3,2))
m

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [427]:
a = np.arange(3)
a

array([0, 1, 2])

In [428]:
m.shape

(3, 2)

In [429]:
a.shape

(3,)

In [430]:
a + m

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

# Numpy Yapisal Arrayler

## Hello ! Good Bye! Numpy

In [494]:
isim = ['ali','veli','isik']
yas = [25,22,19]
boy = [168,159,172]

In [495]:
data = np.zeros(3,dtype={'names':('isim','yas','boy'),'formats':('U10','i4','f8')})

In [496]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [498]:
data['isim'] = isim
data['yas'] = yas
data['boy'] = boy

In [499]:
data

array([('ali', 25, 168.), ('veli', 22, 159.), ('isik', 19, 172.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [500]:
data['isim']

array(['ali', 'veli', 'isik'], dtype='<U10')

In [501]:
data[0]

('ali', 25, 168.)

In [502]:
data[data['yas']<25]['isim']

array(['veli', 'isik'], dtype='<U10')

# PANDAS

## Pandas Series

In [431]:
import numpy as np
import pandas as pd

In [432]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [433]:
seri = pd.Series([1,2,3,4])

In [434]:
type(seri)

pandas.core.series.Series

In [435]:
seri.axes

[RangeIndex(start=0, stop=4, step=1)]

In [436]:
seri.dtype

dtype('int64')

In [437]:
seri.empty # bos deger var mi ?

False

In [438]:
seri.ndim

1

In [439]:
seri.size

4

In [440]:
seri.values

array([1, 2, 3, 4], dtype=int64)

In [441]:
seri.head(2)

0    1
1    2
dtype: int64

In [442]:
seri[0:3]

0    1
1    2
2    3
dtype: int64

In [443]:
seri.tail(2)

2    3
3    4
dtype: int64

In [444]:
## Numpy uzerinden pandas serisi olusturmak

In [445]:
a= np.array([1,2,3,566,88])
a

array([  1,   2,   3, 566,  88])

In [446]:
seri = pd.Series(a)

In [447]:
seri

0      1
1      2
2      3
3    566
4     88
dtype: int32

In [448]:
seri.index

RangeIndex(start=0, stop=5, step=1)

In [449]:
seri[0]

1

In [450]:
pd.Series([1,5,0.9,34], index = [1,3,5,7])

1     1.0
3     5.0
5     0.9
7    34.0
dtype: float64

In [451]:
seri =pd.Series([1,5,0.9,34], index = ['a','b','c','d'])

In [452]:
seri

a     1.0
b     5.0
c     0.9
d    34.0
dtype: float64

In [453]:
seri['a']

1.0

In [454]:
## Sozluk uzerinden Pandas Series

In [455]:
sozluk = {'reg':10,'loj':11,'cart':12}
sozluk

{'reg': 10, 'loj': 11, 'cart': 12}

In [456]:
seri =pd.Series(sozluk)
seri

reg     10
loj     11
cart    12
dtype: int64

In [457]:
seri['reg']

10

In [458]:
seri['reg':'cart']

reg     10
loj     11
cart    12
dtype: int64

In [459]:
pd.concat([seri,seri])

reg     10
loj     11
cart    12
reg     10
loj     11
cart    12
dtype: int64

In [460]:
seri.append(seri)

reg     10
loj     11
cart    12
reg     10
loj     11
cart    12
dtype: int64

In [461]:
seri

reg     10
loj     11
cart    12
dtype: int64

## Serilerde eleman islemleri

In [462]:
seri = pd.Series([121,200,150,99],index = ['reg','loj','cart','rf'])
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [463]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [464]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [465]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [466]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [467]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [468]:
'kln' in seri

False

In [469]:
'reg' in seri

True

In [470]:
seri[['rf','reg']]

rf      99
reg    121
dtype: int64

In [471]:
seri['rf'] = 125
seri

reg     121
loj     200
cart    150
rf      125
dtype: int64

In [472]:
seri['loj':'rf']

loj     200
cart    150
rf      125
dtype: int64

In [473]:
seri

reg     121
loj     200
cart    150
rf      125
dtype: int64

In [474]:
seri[(seri >125) & (seri <200)]

cart    150
dtype: int64

In [475]:
data = pd.Series (['a','b','c'], index =[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [476]:
data[0]

KeyError: 0

In [477]:
data[1]

'a'

In [478]:
data[1:3]

3    b
5    c
dtype: object

In [479]:
data[0:3]

1    a
3    b
5    c
dtype: object

In [487]:
# loc label based indexing , tanimlandigi sekliyle index yakalamak (index adina gore)

In [481]:
data

1    a
3    b
5    c
dtype: object

In [482]:
data.loc[1]

'a'

In [484]:
data.loc[5]

'c'

In [485]:
data.loc[0:1]

1    a
dtype: object

In [486]:
data.loc[0:2]

1    a
dtype: object

In [488]:
data.loc[0:4]

1    a
3    b
dtype: object

In [489]:
# iloc positional based indexing , indexi sifirlayarak yakalamak

In [490]:
data

1    a
3    b
5    c
dtype: object

In [491]:
data.iloc[0]

'a'

In [492]:
data.iloc[0:2]

1    a
3    b
dtype: object

In [493]:
data.iloc[1]

'b'

## Pandas DataFrame Ozellikleri & olusturma